In [1]:
import pandas as pd 
import numpy as np # pip install numpy
s= pd.Series([13,33,21,np.nan,43,22,np.nan,56,78, np.nan])
s

0    13.0
1    33.0
2    21.0
3     NaN
4    43.0
5    22.0
6     NaN
7    56.0
8    78.0
9     NaN
dtype: float64

In [2]:
s.shape

(10,)

In [3]:
s.isnull()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7    False
8    False
9     True
dtype: bool

In [4]:
s.isnull().sum()

np.int64(3)

In [5]:
s[s.isnull()]

3   NaN
6   NaN
9   NaN
dtype: float64

In [6]:
s.isna().sum()

np.int64(3)

In [7]:
s.hasnans

True

In [8]:
s.dropna() #to drop the null values

0    13.0
1    33.0
2    21.0
4    43.0
5    22.0
7    56.0
8    78.0
dtype: float64

In [9]:
s.dropna(ignore_index = True)


0    13.0
1    33.0
2    21.0
3    43.0
4    22.0
5    56.0
6    78.0
dtype: float64

In [10]:
s.mean()

np.float64(38.0)

In [11]:
s.fillna(s.mean(), inplace =True)

0    13.0
1    33.0
2    21.0
3    38.0
4    43.0
5    22.0
6    38.0
7    56.0
8    78.0
9    38.0
dtype: float64

In [12]:
import numpy as np


In [13]:
arr = np.array([12,145,43,21,100])

In [14]:
arr

array([ 12, 145,  43,  21, 100])

In [15]:
arr.ndim

1

In [16]:
arr2 = np.array([12,10,23,45])
arr2

array([12, 10, 23, 45])

In [17]:
arr2.ndim

1

In [20]:
arr2 = np.array([[12,13,14],[89,87,76],[1,2,3]])
arr2

array([[12, 13, 14],
       [89, 87, 76],
       [ 1,  2,  3]])

In [21]:
arr2.ndim

2

In [22]:
arr3= np.array([
    [
        [12,13],
        [23,24]
    ],
    [
        [45,54],
        [22,12]
    ]
])
arr3

array([[[12, 13],
        [23, 24]],

       [[45, 54],
        [22, 12]]])

In [23]:
arr3.ndim

3

In [24]:
arr

array([ 12, 145,  43,  21, 100])

In [25]:
arr.sum()

np.int64(321)

In [26]:
arr3.sum()

np.int64(205)

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
i = np.identity(8)
i

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [30]:
i.ndim

2

In [31]:
i.shape

(8, 8)

In [36]:
i.reshape(16,4)

array([[1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [37]:
i.reshape(2,32)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [38]:
arr2

array([[12, 13, 14],
       [89, 87, 76],
       [ 1,  2,  3]])

In [39]:
arr2.reshape(-1)

array([12, 13, 14, 89, 87, 76,  1,  2,  3])

In [40]:

a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
b= np.array([
    [11,12,13],
    [23,21,11],
    [22,23,33]
])

In [41]:
a+b

array([[12, 14, 16],
       [27, 26, 17],
       [29, 31, 42]])

In [42]:
b

array([[11, 12, 13],
       [23, 21, 11],
       [22, 23, 33]])

In [43]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
a.sum(axis = 1)

array([ 6, 15, 24])

In [45]:
a.sum(axis = 0)

array([12, 15, 18])

In [46]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [47]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])